### PR TITLE
remove opal-browser

### PR DESCRIPTION
**Pull request by fazibear**

### CODE REVIEW

**Comment by elia** [comment]
What about making opal-browser more cherry pickable so that the equivalent of `Inesita::Browser` can be required? 

That seems to be a recurrent theme with virtual dom libs (clearwater does the same, not sure about volt).

cc @meh

**Comment by fazibear** [comment]
@elia That would be really great. I've made this decision because all opal-browser takes about 500KB. Of course there is no problem to use it with you app, but you have to require it by yourself. As I remember you mention somewhere that you want to make opal-browser more cherry pickable before release new version.

**Comment by meh** [comment]
@elia the virtual DOM in opal-browser is basically paggio + a single file that does the conversion from paggio's AST to actual DOM.

Doubt anyone who needs that would even need opal-browser at that point.

**Comment by elia** [comment]
@meh to me opal-browser is basically a live version of MDN :stuck_out_tongue_winking_eye: 

Even if one wants to use opal-jquery it's still very useful for all the other stuff like Kernel#every, websockets, canvas, you name it. To me it should be the go to tool for browser stuff.

**Comment by fazibear** [comment]
I'm still using `opal-browser`, but I don't want to have such a large lib in dependencies. So I just have to add it to Gemfile require it and using it like before.
Anyway opal-browser gem (from rubygems) is outdated. I need to use git version to use `Storege` for example. And just like @elia said. It will be big adventage so I could just require small piece of opal-browser without for example paggio.

**Comment by meh** [comment]
Can you give some more detailed feedback [here](https://github.com/opal/opal-browser/issues/60) please?

Once I know more I'll split stuff up and release a new gem version.

**Pull request merged**
